# Generated by Django 4.0.3 on 2022-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=15)),
                ('maintext', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
